### ISSUE TITLE
cancel not shutting down process

### ISSUE THREAD

**Issue by joemiller** [pantheon-systems/pauditd#20]
We have seen one case in the wild where this line: https://github.com/pantheon-systems/pauditd/blob/f96a1e12ab12242ab1ba8340b29ae899d66046b7/pkg/output/http_writer_config.go#L71 was hit but the process did not shut down as expected. Need to look into this. It should happen far less often since we switched to using the pollwatcher with certinel instead of the inotify watcher which is racy.

**Comment by CSdread** [comment]
This is completed
